#!/usr/bin/env node
/**
 * UserPromptSubmit: pull cloud-side file changes (images/audio generated by
 * `gipity chat`, web-side edits) before the next turn so the agent sees
 * current state.
 *
 * No-ops unless the working directory is a Gipity project (.gipity.json
 * present). When files changed, emits a systemMessage so the agent knows the
 * tree moved underneath it. Always exits 0 - sync trouble must never block
 * the user's prompt.
 *
 * RATE-LIMITED: the full reconcile blocks the user's prompt, and back-to-back
 * turns almost never have new cloud-side files. If this hook completed a pull
 * in the last PULL_INTERVAL_MS (marker file below), skip - remote changes are
 * picked up at most one interval later, and `gipity sync` remains the manual
 * catch-up (it never rate-limits). Only OUR completed pulls stamp the marker;
 * pushes don't count.
 *
 * Override: set GIPITY_PULL_INTERVAL_MS to tune the window per session or
 * machine - `0` disables the rate limit entirely (pull on every prompt, the
 * pre-rate-limit behavior). Unset/invalid falls back to the 15s default.
 */
'use strict';
const { existsSync, statSync, writeFileSync, mkdirSync } = require('fs');
const { join } = require('path');
const { exec } = require('child_process');

const MARKER = join('.gipity', 'last-pull');
const envInterval = Number(process.env.GIPITY_PULL_INTERVAL_MS);
const PULL_INTERVAL_MS = Number.isFinite(envInterval) && envInterval >= 0 ? envInterval : 15_000;

if (!existsSync('.gipity.json')) process.exit(0);

try {
  if (PULL_INTERVAL_MS > 0 && Date.now() - statSync(MARKER).mtimeMs < PULL_INTERVAL_MS) process.exit(0);
} catch { /* no marker yet - pull */ }

exec('gipity sync --json', (err, out) => {
  if (err) process.exit(0);
  try {
    mkdirSync('.gipity', { recursive: true });
    writeFileSync(MARKER, '');
  } catch { /* marker is best-effort */ }
  try {
    const r = JSON.parse(out);
    if (r.applied > 0) {
      console.log(JSON.stringify({ systemMessage: 'Gipity sync: ' + (r.summary || 'Files changed.') }));
    }
  } catch { /* ignore malformed output */ }
  process.exit(0);
});
