#!/usr/bin/env node
/**
 * UserPromptSubmit: pull cloud-side file changes (images/audio generated by
 * `gipity chat`, web-side edits) before the next turn so the agent sees
 * current state.
 *
 * No-ops unless the working directory is a Gipity project (.gipity.json
 * present). When files changed, emits a systemMessage so the agent knows the
 * tree moved underneath it. Always exits 0 - sync trouble must never block
 * the user's prompt.
 */
'use strict';
const { existsSync } = require('fs');
const { exec } = require('child_process');

if (!existsSync('.gipity.json')) process.exit(0);

exec('gipity sync --json', (err, out) => {
  if (err) process.exit(0);
  try {
    const r = JSON.parse(out);
    if (r.applied > 0) {
      console.log(JSON.stringify({ systemMessage: 'Gipity sync: ' + (r.summary || 'Files changed.') }));
    }
  } catch { /* ignore malformed output */ }
  process.exit(0);
});
